[versions]
kotlin = "2.3.0"
uuid-creator = "6.1.1"
mockito-kotlin = "6.2.3"
junit = "6.0.3"

[libraries]
uuid-creator = { module = "com.github.f4b6a3:uuid-creator", version.ref = "uuid-creator" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }